### ISSUE TITLE
openssl TLS demo core dump

### ISSUE THREAD

**Issue by jhfeng** [open-quantum-safe/openssl#179] opened 2020-05-07 15:38 UTC
I follow the README instruction to build liboqs and openssl in a Ubuntu 18.04. 
After that, I want to do a quick test with build openssl s_server / s_client with instruction in README:

First, I created a self-signed certificate 2 commands:

1) $ apps/openssl ecparam -name secp384r1 -genkey -param_enc explicit -out private-key.pem
2) $ apps/openssl req -new -x509 -key private-key.pem -out server-cert.pem -days 365 -config apps/openssl.cnf

Now I try TLS1.3 connection with openssl s_server / s_client:

1) in first terminal, start server:
```
$ apps/openssl s_server -cert server-cert.pem -key private-key.pem -www -tls1_3
Using default temp DH parameters
ACCEPT
```
2) in second terminal, start client:
```
$ apps/openssl s_client -groups kyber512 -CAfile server-cert.pem
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 1111 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
3) now back to server terminal, server core dumped
```
Using default temp DH parameters
ACCEPT
Segmentation fault (core dumped)
```

4) interestingly, if I specify non-443 port number in s_server command, I can get core dump when starting server 
```
$ sudo apps/openssl s_server -cert server-cert.pem -key private-key.pem -www -tls1_3 -accept 4443
Using default temp DH parameters
ACCEPT
Segmentation fault
```

Do I have some misconfiguration ? or running command with wrong parameters ?

**Comment by baentsch** [comment] 2020-05-08 05:50
@jhfeng Thanks for this report. I cannot reproduce this behaviour as described, though (on Ubuntu 18.04, x86_64). Can you please share how you built the oqs-openssl that you are running above? Did you follow _exactly_ the documentation or set any `Configure` parameters differently (e.g., OQS_DEFAULT_GROUPS or use shared libraries)? What output do you get if you run `ldd apps/openssl`?

**Comment by baentsch** [comment] 2020-05-15 11:40
@jhfeng Closing this issue for now. Please re-open if you encounter this again: In that case, please also provide steps to reproduce.

**Closed as completed by baentsch** 2020-05-15 11:40 UTC
